webapp/models.py
from webapp import db, bcrypt
from sqlalchemy.ext.hybrid import hybrid_method, hybrid_property
from datetime import datetime

from flask_admin.contrib import sqla
from flask_admin.contrib.sqla import ModelView

class Mantan(db.Model):

	__tablename__ = "mantans"

	id = db.Column(db.Integer, primary_key=True)
	nama_mantan = db.Column(db.String, nullable=False)
	alasan_putus = db.Column(db.String, nullable=False)

	def __init__(self, nama="", alasan=""):
		self.nama_mantan = nama
		self.alasan_putus = alasan

	def __repr__(self):
		return '<title {}'.format(self.name)

class User(db.Model):

	__tablename__ = 'users'

	id = db.Column(db.Integer, primary_key=True, autoincrement=True)
	email = db.Column(db.String, unique=True, nullable=False)
	plaintext_password = db.Column(db.String, nullable=False)
	# _password = db.Column(db.Binary(60), nullable=False)
	authenticated = db.Column(db.Boolean, default=False)
	# email_confirmation_sent_on = db.Column(db.DateTime, nullable=True)
	# email_confirmed = db.Column(db.Boolean, nullable=True, default=False)
	# email_confirmed_on = db.Column(db.DateTime, nullable=True)
	registered_on = db.Column(db.DateTime, nullable=True)
	last_logged_in = db.Column(db.DateTime, nullable=True)
	current_logged_in = db.Column(db.DateTime, nullable=True)
	role = db.Column(db.String, default='user')

	# the __init__() method is defined as the Constructor
	def __init__(self, email="", plaintext_password="", role="user"):
		self.email = email
		# self.plaintext_password = password = plaintext_password
		self.plaintext_password = plaintext_password
		self.authenticated = False
		# self.email_confirmation_sent_on = email_confirmation_sent_on
		# self.email_confirmed = False
		# self.email_confirmed_on = None
		# self.registered_on = datetime.now()
		# self.last_logged_in = None
		# self.current_logged_in = datetime.now()
		self.role = role

	@hybrid_property
	def password(self):
		return self._password

	@password.setter
	def set_password(self, plaintext_password):
		self._password = bcrypt.generate_password_hash(plaintext_password)

	@hybrid_method
	def is_correct_password(self, plaintext_password):
		# return self.password_plaintext == plaintext_password
		return bcrypt.check_password_hash(self.password, plaintext_password)

	@property
	def is_authenticated(self):
		"""Return True if the user is authenticated."""
		return self.authenticated

	@property
	def is_active(self):
		"""Always Trye, as all users aer active."""
		return True

	@property
	def is_anonymous(self):
		"""Always false, as anonymous users aren't supported."""
		return False

	def get_id(self):
		"""Return the email address to satisfy flask login requirements"""
		"""requires use of python 3"""
		return str(self.id)

	 # __repr__() is defined to provide a printable representation of each Recipe object
	def __repr__(self):
		return '<user {0}>'.format(self.name)

webapp/kode/forms.py
from flask_wtf import Form
from wtforms import StringField
from wtforms.validators import DataRequired

class AddMantanForm(Form):
	nama_mantan = StringField('Nama Mantan', validators=[DataRequired()])
	alasan_putus = StringField('Alasan Putus', validators=[DataRequired()])

webapp/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_debugtoolbar import DebugToolbarExtension

app = Flask(__name__, instance_relative_config=True)
app.config.from_pyfile('flask.cfg')

# app.config.from_object(os.environ['APP_SETTINGS'])
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

DEBUG_TB_INTERCEPT_REDIRECTS = False
toolbar = DebugToolbarExtension(app)

db = SQLAlchemy(app)
bcrypt = Bcrypt(app)
# mail = Mail(app)

# flask login
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = "users.login"

from webapp.models import User, Mantan
from webapp import admin

@login_manager.user_loader
def load_user(user_id):
	return User.query.filter(User.id == int(user_id)).first()

# from . import views
from webapp.users.views import users_blueprint
from webapp.kode.views import kode_blueprint

# register the blueprint
app.register_blueprint(users_blueprint)
app.register_blueprint(kode_blueprint)

webapp/kode/views.py
from flask import render_template, Blueprint, request, redirect, flash, url_for
from webapp.models import Mantan

from .forms import AddMantanForm
from webapp import db

kode_blueprint = Blueprint('kode', __name__, template_folder='templates')

@kode_blueprint.route('/')
def index():
	all_mantans = Mantan.query.all()
	return render_template('mantans.html',
							mantans=all_mantans)

@kode_blueprint.route('/add', methods=['GET', 'POST'])
def add_mantan():
	form = AddMantanForm(request.form)
	if request.method == 'POST':
		if form.validate_on_submit():
			new_mantan = Mantan(form.nama_mantan.data, form.alasan_putus.data)
			db.session.add(new_mantan)
			db.session.commit()
			flash('New mantan, {}, added!'.format(new_mantan.nama_mantan), 'success')
			return redirect(url_for('kode.index'))
		else:
			# flash_error(form)
			flash('ERROR! Mantan was not added.', 'error')
	return render_template('add_mantan.html',
							form=form)

webapp/users/views.py
from flask import render_template, Blueprint, request, flash, url_for, redirect
from .form import RegisterForm, LoginForm, EmailForm, PasswordForm
from sqlalchemy.exc import IntegrityError
from flask_login import login_required, login_user, logout_user, current_user
from datetime import datetime

from webapp.models import User
from webapp import db

users_blueprint = Blueprint('users', __name__)

@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
	form = LoginForm(request.form)
	if request.method == 'POST':
		if form.validate_on_submit():
			user = User.query.filter_by(email=form.email.data).first()
			if user is not None and user.is_correct_password(form.password.data):
				user.authenticated = True
				user.last_logged_in = user.current_logged_in
				user.current_logged_in = datetime.now()
				db.session.add(user)
				db.session.commit()
				login_user(user)
				flash('Thanks for logging in, {}'.format(current_user.email))
				return redirect('/')
			else:
				flash('ERROR! Incorrect login credentials.', 'error')
	return render_template('login.html', form=form)

@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
	form = RegisterForm(request.form)
	if request.method == 'POST':
		if form.validate_on_submit():
			try:
				new_user = User(form.email.data, form.password.data)
				new_user.authenticated = True
				db.session.add(new_user)
				db.session.commit()
				login_user(new_user)

				flash('Thanks for registering!', 'success')
				return redirect('/')
			except IntegrityError:
				db.session.rollback()
				flash('ERROR! Email ({}) already exists.'.format(form.email.data), 'error')
	return render_template('register.html', form=form)

@users_blueprint.route('/logout')
@login_required
def logout():
	user = current_user
	user.authenticated = False
	db.session.add(user)
	db.session.commit()
	logout_user()
	flash('Goodbye!', 'info')
	return redirect(url_for('users.login'))

@users_blueprint.route('/user_profile')
@login_required
def user_profile():
	return render_template('user_profile.html')

@users_blueprint.route('/email_change', methods=["GET", "POST"])
@login_required
def user_email_change():
	form = EmailForm()
	if request.method == 'POST':
		if form.validate_on_submit():
			try:
				user_check = User.query.filter_by(email=form.email.data).first()
				if user_check is None:
					user = current_user
					user.email = form.email.data
					db.session.add(user)
					db.session.commit()
					flash('Email changed!')
					return redirect('/')
				else:
					flash('Sorry, that email already exist', 'error')
			except IntegrityError:
				flash('Sorry, that email already exist', 'error')
	return render_template('email_change.html', form=form)

@users_blueprint.route('/password_change', methods=["GET", "POST"])
@login_required
def user_password_change():
	form = PasswordForm()
	if request.method == 'POST':
		if form.validate_on_submit():
			user = current_user
			user.password = form.password.data
			db.session.add(user)
			db.session.commit()
			flash('Password has been updated!', 'success')
			return redirect(url_for('users.user_profile'))

	return render_template('password_change.html', form=form)


@users_blueprint.route('/admin')
@login_required
def admin():
	pass

webapp/templates/_form_macros.html
{% macro render_field(field) %}

<dt>{{ field.label }}:

<dd>{{ field(**kwargs)|safe }}
	{% if field.errors %}
		<span class="error">
			{% for error in field.errors %}
				{{ error }}
			{% endfor %}
		</span>
	{% endif %}
<dd>

{% endmacro %}

webapp/templates/add_mantan.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="add-mantan">
	<div class="page-header">
		<h2>App Tambah Mantan</h2>
	</div>

	<form action="{{ url_for('kode.add_mantan') }}" method="post">
	 <!-- form contents should be sent to the add_mantan() function in the kode Blueprint using the ‘POST’ HTTP method -->
		{{ form.csrf_token }}
		<dl>
			{{ render_field(form.nama_mantan, placeholder="Tambah nama mantan") }}
			{{ render_field(form.alasan_putus, placeholder="Alasan putus") }}
		</dl>
		
		<button class="btn btn-sm btn-success" type="submit">Tambahkan Mantan</button>
	</form>
</div>
{% endblock %}

webapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %} - Flask Webapp</title>
    <!-- styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

  </head>
 
  <body>
 
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
 
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mantans-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('kode.index') }}">App daftar mantan</a>
        </div>
 
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="mantans-navbar-collapse-1">
          <ul class="nav navbar-nav">
            {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('kode.add_mantan') }}">Add</a></li>
              <li><a href="{{ url_for('users.user_profile') }}">{{ current_user.email }}</a></li>
            {% endif %}
            {% if current_user.role == "admin" %}
            <li><a href="{{ url_for('users.admin') }}">Admin</a></li>
            {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('users.logout') }}">Log Out</a></li>
            {% else %}
              <li><a href="{{ url_for('users.login') }}">Log In</a></li>
              <li><a href="{{ url_for('users.register') }}">Register</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div><!-- /.container -->
    </nav>
 
    <div class="container">
      <div class="content">

        <!-- flash message -->
        {% for error_message in get_flashed_messages(category_filter=["error"]) %}
          <div class="alert alert-danger alert-dismissible">{{ error_message }}</div>
        {% endfor %}

        {% for success_message in get_flashed_messages(category_filter=["success"]) %}
          <div class="alert alert-success alert-dismissible">{{ success_message }}</div>
        {% endfor %}

        {% for infor_message in get_flashed_messages(category_filter=["info"]) %}
          <div class="alert alert-info alert-dismissible">{{ infor_message }}</div>
        {% endfor %}
 
        <!-- child template -->
        {% block content %}
        {% endblock %}
 
      </div>
      <div class="footer">
        <hr>
        <p>2016 - Flask webapp</p>
      </div>
    </div><!-- /.container -->
 
    <!-- scripts -->
    <script src="{{ url_for('static', filename='js/bootstap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
  </body>
</html>

webapp/templates/email_change.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

	<div class="user-profile">
		<div class="page-header">
			<h2>Email Change</h2>
		</div>

		<h3>Current Email: {{ current_user.email }}</h3>
		<h3>Please enter your new email: </h3>
		<form action="{{ url_for('users.user_email_change') }}" method="POST">
			{{ form.csrf_token }}
			<dl>{{ render_field(form.email, placeholder="Enter new email address") }}</dl>
			<button class="btn btn-sm btn-success" type="submit">Update</button>
		</form>
	</div>

{% endblock %}

webapp/templates/login.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

  <div class="user-registration">
    <div class="page-header">
      <h2>Log In</h2>
    </div>

    <form action="{{ url_for('users.login') }}" method="post">
      {{ form.csrf_token }}
      <dl>
        {{ render_field(form.email, placeholder="Email address") }}
        {{ render_field(form.password, placeholder="Password") }}
      </dl>
      <button class="btn btn-sm btn-success" type="submit">Log In</button>
    </form>
    <em>Need an account? </em><a href="/register">Signup!</a>
    <!-- <p><em>Forgot your password? </em><a href="/reset">Reset!!</a></p> -->
  </div>

{% endblock %}

webapp/templates/mantans.html
{% extends "base.html" %}
{% block title %}App daftar mantan{% endblock %}

{% block content %}
    <div class="page-header">
      <h2>Mantan</h2>
    </div>
    <div class="row">
      <div class="col-md-4">
        <table class="table table-striped" id="owned_stock_table">
          <thead>
            <tr>
              <th>Nama</th>
              <th>Alasan putus</th>
            </tr>
          </thead>
          <tbody>
            {% for mantan in mantans %}
            <tr>
              <td>{{ mantan.nama_mantan }}</td>
              <td>{{ mantan.alasan_putus }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

{% endblock %}

webapp/templates/password_change.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}
	<div class="user-profile">
		<div class="page-header">
			<h2>Password Change</h2>
		</div>

		<form action="{{ url_for('users.user_password_change') }}" method="POST">
			{{ form.csrf_token }}
			<dl>{{ render_field(form.password, placeholder="Enter new password") }}</dl>
			<button class="btn btn-sm btn-success" type="submit">Update</button>
		</form>
	</div>

{% endblock %}

webapp/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% from "_form_macros.html" import render_field %}

{% block content %}
<div class="user-registration">
	<div class="page-header">
		<h2>Please Register your new account</h2>
	</div>

	<form action="{{ url_for('users.register') }}" method="post">
		{{ form.csrf_token }}
		<dl>
			{{ render_field(form.email, placeholder="Email address") }}
			{{ render_field(form.password, placeholder="Password") }}
			{{ render_field(form.confirm, placeholder="Confirm password") }}
		</dl>
		<button class="btn btn-sm btn-success" type="submit">Create New Account</button>
	</form>
</div>
{% endblock %}

webapp/templates/reset_password_with_token.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="add-recipe">
    <div class="page-header">
        <h2>New Password:</h2>
    </div>
    <form action="{{ url_for('users.reset_with_token', token=token) }}" method="POST">
        {{ form.csrf_token }}
        <dl>{{ render_field(form.password, placeholder="Enter New Password") }}</dl>
        <button class="btn btn-sm btn-success" type="submit">Update</button>
    </form>
</div>

{% endblock %}

webapp/templates/user_profile.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="user-profile">
	<div class="page-header">
		<h2>User Profile</h2>
	</div>

	<div class="row">
		<div class="col-sm-6">
			<div class="panel panel-primary">
				<div class="panel-heading">Email Address</div>
				<div class="panel-body">{{ current_user.email }}</div>
			</div>

			<div class="panel panel-info">
				<div class="panel-heading">Account Actions</div>
				<div class="panel-body"><a href="{{ url_for('users.user_email_change') }}">Change Email</a></div>
				<div class="panel-body"><a href="{{ url_for('users.user_password_change') }}">Change Password</a></div>
			</div>

			<div class="panel panel-info">
				<div class="panel-heading">Statistics</div>
				<div class="panel-body">Member since: {{ current_user.registered_on.strftime("%A %B %d, %Y") }}</div>
				{% if current_user.last_logged_in != None %}
					<div class="panel-body">Last Logged In: {{ current_user.registered_on.strftime("%A %B %d, %Y") }}</div>
				{% else %}
					<div class="panel-body">First time logged in. Welcome!</div>
				{% endif %}
			</div>
		</div>
	</div>
</div>

{% endblock %}